# alembic/versions/20230816_initial_schema.py

"""initial schema

Revision ID: 20230816_initial_schema
Revises: 
Create Date: 2023-08-16 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20230816_initial_schema'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('invoice_name_lookup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parsed_name', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parsed_name')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('buyer', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('total_sum', sa.Numeric(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirming', 'confirmed', 'exported', name='invoicestatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('parsed_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('sum', sa.Numeric(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('json_draft', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_state')
    op.drop_table('invoice_items')
    op.drop_table('invoices')
    op.drop_table('invoice_name_lookup')
    op.drop_table('products')
    # ### end Alembic commands ###
