"""init schema

Revision ID: 2e24b7c298b3
Revises: 20230816_initial_schema
Create Date: 2025-04-28 04:57:30.179214+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e24b7c298b3'
down_revision: Union[str, None] = '20230816_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_name_lookup')
    op.drop_table('invoice_state')
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('invoice_items', 'match_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.drop_constraint('invoice_items_invoice_id_fkey', 'invoice_items', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_items', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.add_column('invoices', sa.Column('supplier_name', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('buyer_name', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('raw_text', sa.Text(), nullable=True))
    op.alter_column('invoices', 'status',
               existing_type=postgresql.ENUM('pending', 'confirming', 'confirmed', 'exported', name='invoicestatus'),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('invoices', 'buyer')
    op.drop_column('invoices', 'supplier')
    op.drop_column('invoices', 'total_sum')
    op.drop_constraint('products_name_key', 'products', type_='unique')
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.create_unique_constraint('products_name_key', 'products', ['name'])
    op.add_column('invoices', sa.Column('total_sum', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('supplier', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('buyer', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('invoices', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('pending', 'confirming', 'confirmed', 'exported', name='invoicestatus'),
               existing_nullable=True)
    op.drop_column('invoices', 'raw_text')
    op.drop_column('invoices', 'buyer_name')
    op.drop_column('invoices', 'supplier_name')
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.create_foreign_key('invoice_items_invoice_id_fkey', 'invoice_items', 'invoices', ['invoice_id'], ['id'])
    op.alter_column('invoice_items', 'match_confidence',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.create_table('invoice_state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('json_draft', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='invoice_state_pkey'),
    sa.UniqueConstraint('chat_id', name='invoice_state_chat_id_key')
    )
    op.create_table('invoice_name_lookup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parsed_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='invoice_name_lookup_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='invoice_name_lookup_pkey'),
    sa.UniqueConstraint('parsed_name', name='invoice_name_lookup_parsed_name_key')
    )
    # ### end Alembic commands ###
