"""add product_name_lookup

Revision ID: 3b22e234a8e2
Revises: 2e24b7c298b3
Create Date: 2025-04-28 05:03:16.742881+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b22e234a8e2'
down_revision: Union[str, None] = '2e24b7c298b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_name_lookups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_index('ix_products_name', table_name='products')
    op.create_unique_constraint(None, 'products', ['name'])
    op.drop_column('products', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('unit', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='unique')
    op.create_index('ix_products_name', 'products', ['name'], unique=True)
    op.drop_table('product_name_lookups')
    # ### end Alembic commands ###
