"""add code to supplier & product

Revision ID: 4c2b8ba4b25c
Revises: c4bb15243242
Create Date: 2025-04-28 05:53:02.705584+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c2b8ba4b25c'
down_revision: Union[str, None] = 'c4bb15243242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('code', sa.String(length=64), nullable=True))
    op.add_column('products', sa.Column('uom', sa.String(length=16), nullable=True))
    op.add_column('products', sa.Column('pack_qty', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('products', sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=True))
    op.create_unique_constraint(op.f('uq_products_code'), 'products', ['code'])
    op.drop_column('products', 'default_price')
    op.drop_column('products', 'unit')
    op.add_column('suppliers', sa.Column('code', sa.String(length=64), nullable=True))
    op.create_unique_constraint(op.f('uq_suppliers_code'), 'suppliers', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_suppliers_code'), 'suppliers', type_='unique')
    op.drop_column('suppliers', 'code')
    op.add_column('products', sa.Column('unit', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('default_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('uq_products_code'), 'products', type_='unique')
    op.drop_column('products', 'cost')
    op.drop_column('products', 'pack_qty')
    op.drop_column('products', 'uom')
    op.drop_column('products', 'code')
    # ### end Alembic commands ###
