"""add supplier→invoice FK

Revision ID: c4bb15243242
Revises: d4361ca40d88
Create Date: 2025-04-28 05:50:53.387684+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4bb15243242'
down_revision: Union[str, None] = 'd4361ca40d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('supplier_id', sa.Integer(), nullable=False))
    op.add_column('invoices', sa.Column('document_date', sa.Date(), nullable=True))
    op.drop_index('ix_invoices_invoice_date', table_name='invoices')
    op.create_index(op.f('ix_invoices_supplier_id'), 'invoices', ['supplier_id'], unique=False)
    op.create_foreign_key(op.f('fk_invoices_supplier_id_suppliers'), 'invoices', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    op.drop_column('invoices', 'supplier')
    op.drop_column('invoices', 'invoice_date')
    op.drop_column('invoices', 'number')
    op.drop_constraint('uq_suppliers_name', 'suppliers', type_='unique')
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.create_unique_constraint('uq_suppliers_name', 'suppliers', ['name'])
    op.add_column('invoices', sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('supplier', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_invoices_supplier_id_suppliers'), 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_supplier_id'), table_name='invoices')
    op.create_index('ix_invoices_invoice_date', 'invoices', ['invoice_date'], unique=False)
    op.drop_column('invoices', 'document_date')
    op.drop_column('invoices', 'supplier_id')
    # ### end Alembic commands ###
