"""fix invoice relationships

Revision ID: da128bb6c3f6
Revises: 94631797fa74
Create Date: 2025-04-28 05:24:17.516219+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da128bb6c3f6'
down_revision: Union[str, None] = '94631797fa74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_name_lookup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parsed_name', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_invoice_name_lookup_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_name_lookup'))
    )
    op.create_index(op.f('ix_invoice_name_lookup_parsed_name'), 'invoice_name_lookup', ['parsed_name'], unique=True)
    op.drop_table('product_name_lookups')
    op.alter_column('invoice_items', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_product_id'), 'invoice_items', ['product_id'], unique=False)
    op.drop_constraint('invoice_items_product_id_fkey', 'invoice_items', type_='foreignkey')
    op.drop_constraint('invoice_items_invoice_id_fkey', 'invoice_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_invoice_items_product_id_products'), 'invoice_items', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_invoice_items_invoice_id_invoices'), 'invoice_items', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.drop_column('invoice_items', 'unit')
    op.drop_column('invoice_items', 'sum')
    op.drop_column('invoice_items', 'name')
    op.add_column('invoices', sa.Column('invoice_date', sa.Date(), nullable=False))
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.drop_column('invoices', 'total_sum')
    op.drop_column('invoices', 'buyer')
    op.drop_column('invoices', 'issued_at')
    op.add_column('products', sa.Column('unit', sa.String(length=32), nullable=True))
    op.add_column('products', sa.Column('default_price', sa.Float(), nullable=True))
    op.drop_constraint('products_name_key', 'products', type_='unique')
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.create_unique_constraint('products_name_key', 'products', ['name'])
    op.drop_column('products', 'default_price')
    op.drop_column('products', 'unit')
    op.add_column('invoices', sa.Column('issued_at', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('buyer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('total_sum', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_column('invoices', 'invoice_date')
    op.add_column('invoice_items', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('invoice_items', sa.Column('sum', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('invoice_items', sa.Column('unit', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_invoice_items_invoice_id_invoices'), 'invoice_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_invoice_items_product_id_products'), 'invoice_items', type_='foreignkey')
    op.create_foreign_key('invoice_items_invoice_id_fkey', 'invoice_items', 'invoices', ['invoice_id'], ['id'])
    op.create_foreign_key('invoice_items_product_id_fkey', 'invoice_items', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_invoice_items_product_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.alter_column('invoice_items', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_table('product_name_lookups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_name_lookups_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_name_lookups_pkey'),
    sa.UniqueConstraint('name', name='product_name_lookups_name_key')
    )
    op.drop_index(op.f('ix_invoice_name_lookup_parsed_name'), table_name='invoice_name_lookup')
    op.drop_table('invoice_name_lookup')
    # ### end Alembic commands ###
