name: CI          # отображается в списке Actions

on: [push, pull_request]   # запуск при push и PR

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .       # добавляет корень репо в импорт-путь
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11       # нужная версия

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q
