name: CI / Lint & Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install ruff mypy pytest

    # ---------- СИНТАКС + LINT ----------
    - name: Ruff lint (сразу ловит синтаксические ошибки)
      run: |
        ruff check .

    - name: Py-compile (доп. гарантия SyntaxError = fail)
      run: |
        python - <<'PY'
        import subprocess, pathlib, sys
        files = [str(p) for p in pathlib.Path('.').rglob('*.py')]
        if files:
            cmd = [sys.executable, '-m', 'py_compile', *files]
            subprocess.run(cmd, check=True)
        PY

    # ---------- ТИПИЗАЦИЯ (необязательно) ----------
    - name: Mypy type-check
      run: mypy .

    # ---------- ТЕСТЫ (необязательно) ----------
    - name: Pytest
      run: pytest -q
